# Generated by Django 5.2 on 2025-04-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, to='chatbot.question'),
        ),
    ]
