# Generated by Django 5.2 on 2025-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_usersession_answered_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
