# Generated by Django 5.2 on 2025-04-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_usersession_last_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='last_message_id',
        ),
    ]
