# Generated by Django 5.2 on 2025-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_usersession_last_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='topic_page',
            field=models.IntegerField(default=1),
        ),
    ]
