# Generated by Django 5.2 on 2025-06-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_usersession_topic_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='topic_page',
        ),
    ]
